#!/bin/bash
# Assignment 1: System Report Script
# Course: COMP2137 - Linux Automation
# Author: Regin Ian Pioquinto
# Description: Displays system information and status in an organized report.

# Redirect all error messages to /dev/null so they don’t show in output
exec 2>/dev/null

# -------------------------
# Collect system information
# -------------------------

# Basic details
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date)

# Operating System info
source /etc/os-release
OS="$NAME $VERSION"

# Uptime
UPTIME=$(uptime -p)

# CPU info
#CPU=$(lshw -class processor | grep "product:" | awk -F': ' '{print $2}')
CPU=$(lshw -class processor | grep "product:" | awk -F': ' '{print $2}' | head -n 1)


# RAM info
RAM=$(free -h | awk '/Mem:/ {print $2}')

# Disk info
DISKS=$(lshw -class disk | grep "product:" | awk -F': ' '{print $2}' | xargs)

# Video info
VIDEO=$(lshw -class display | grep "product:" | awk -F': ' '{print $2}')

# IP address for the default interface
DEFAULT_INTERFACE=$(ip route | awk '/default/ {print $5; exit}')
HOST_ADDRESS=$(ip -4 addr show $DEFAULT_INTERFACE | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

# Gateway IP
GATEWAY_IP=$(ip route | awk '/default/ {print $3; exit}')

# DNS Server
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | tr '\n' ',' | sed 's/,$//')

# -------------------------
# Collect system status
# -------------------------

# Users logged in
USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')

# Disk space
DISK_SPACE=$(df -h --local | awk 'NR>1 {printf "%s %s free\n", $6, $4}')

# Process count
PROCESS_COUNT=$(ps -e --no-headers | wc -l)

# Load averages
LOAD_AVERAGES=$(uptime | awk -F'load average: ' '{print $2}')

# Listening ports
LISTENING_PORTS=$(ss -tuln | awk '/LISTEN/ {print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | tr '\n' ',' | sed 's/,$//')

# Firewall status
UFW_STATUS=$(sudo ufw status | head -n 1)

# -------------------------
# Display report
# -------------------------

echo ""
cat <<EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATE

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS_LOGGED_IN
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS
EOF
echo ""
